local key = require("barney.lib.keymap")
local trouble = require("trouble")
trouble.setup()
key.nmap("<leader>dl", "<cmd>Trouble<cr>", "[d]iagnostics [l]ist")
key.nmap("<leader>dJ", function()
  trouble.next({ jump = true })
end, "[d]iagnostic next across files")
key.nmap("<leader>dK", function()
  trouble.prev({ jump = true })
end, "[d]iagnostic prev across files")
