vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.wrap = false
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.undodir = vim.fn.stdpath("data") .. "/undo"
vim.opt.undofile = true
vim.opt.hlsearch = true
vim.opt.incsearch = true
vim.opt.scrolloff = 8
vim.opt.sidescrolloff = 8
vim.opt.updatetime = 50
vim.opt.colorcolumn = "120"
vim.opt.termguicolors = true
vim.opt.completeopt = "menuone,noselect"
vim.opt.clipboard = "unnamed,unnamedplus"
vim.opt.splitright = true
vim.opt.autoread = true
vim.opt.winborder = "rounded"
vim.opt.list = true
vim.opt.listchars = {
  tab = "⎸ ",
  trail = "·",
  extends = "»",
  precedes = "«",
}
